Fix Stripe interception in Python 2.
Previously this failed with:

AttributeError: 'NoneType' object has no attribute 'path'

Seems to be because Python 2 loses all imports when we delete
sys.modules['stripe'] to reset it, even for the code still
running in that module (!). Tested with 2.7.15+. Now works
both with that & Python 3.6.8.